import numpy as np

from typing import Protocol, List, Dict

Array = np.ndarray
FloatArray = np.ndarray
IntArray = np.ndarray

class FeatureProvider(Protocol):
    def vector(self) -> Array: ...
    def names(self) -> List[str]: ...
    def clamp_(self) -> None: ...
    def to_dict(self) -> Dict: ...
    @classmethod
    def from_dict(cls, d: Dict): ...
    def to_phase_model(self, *args, **kwargs): ...

