from typing import Dict, List, Protocol

from powergrid.utils.typing import Array


class FeatureProvider(Protocol):
    def vector(self) -> Array: ...
    def names(self) -> List[str]: ...
    def clamp_(self) -> None: ...
    def to_dict(self) -> Dict: ...
    @classmethod
    def from_dict(cls, d: Dict): ...
    def to_phase_model(self, *args, **kwargs): ...